# Generated by Django 6.0.5 on 2026-05-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
