# Generated by Django 6.0.5 on 2026-05-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_add_display_name_to_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
